@startuml
header Topologi Jaringan Komputer
footer Copyright@2024
title TOPOLOGI SIMPLE PLAN
nwdiag {
    inet --router

    network ether1{
        color = "lightblue"
        router [adress = "192.168.88.0/27"]
    }

    network ether2{
        router [adress = "192.168.99.0/29"]
    }

    network ether3{
        router [adress = "192.168.77.0/28"]
    }

    network ether4{
        router [adress = "192.168.66.0/32"]
    }
}